file_format: "1"
id: skullkeys
name: Skullkeys
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - skullkeys_left
  - skullkeys_right
